-- ============================================================
-- PRY2204 - SEMANA 8
-- MODELAMIENTO DE BASES DE DATOS
-- TALLER MECANICO MIKES LTDA.
-- ============================================================


-- ============================================================
-- DROP DE TABLAS
-- ============================================================

DROP TABLE DETALLE_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE MANTENCION CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE AUTOMOVIL CASCADE CONSTRAINTS;
DROP TABLE PREMIUM CASCADE CONSTRAINTS;
DROP TABLE ESTANDAR CASCADE CONSTRAINTS;
DROP TABLE MECANICO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TIPO_AUTOMOVIL CASCADE CONSTRAINTS;
DROP TABLE MODELO CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_SERVICIO;
DROP SEQUENCE SEQ_CIUDAD;



-- ============================================================
-- CASO 1
-- IMPLEMENTACION DEL MODELO RELACIONAL
-- ============================================================


-- ============================================================
-- 1. TABLA PAIS
-- Identity inicia en 9 e incrementa en 3
-- ============================================================

CREATE TABLE PAIS (
    id_pais NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 9 INCREMENT BY 3),

    nom_pais VARCHAR2(30) NOT NULL,

    CONSTRAINT PAIS_PK
        PRIMARY KEY (id_pais)
);


-- ============================================================
-- 2. TABLA CIUDAD
-- ============================================================

CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3) NOT NULL,
    nom_ciudad VARCHAR2(30) NOT NULL,
    cod_pais NUMBER(3) NOT NULL,

    CONSTRAINT CIUDAD_PK
        PRIMARY KEY (id_ciudad),

    CONSTRAINT CIUDAD_FK_PAIS
        FOREIGN KEY (cod_pais)
        REFERENCES PAIS(id_pais)
);


-- ============================================================
-- 3. TABLA SUCURSAL
-- ============================================================

CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3) NOT NULL,
    nom_sucursal VARCHAR2(20) NOT NULL,
    calle VARCHAR2(20) NOT NULL,
    num_calle NUMBER(4) NOT NULL,
    cod_ciudad NUMBER(3) NOT NULL,

    CONSTRAINT SUCURSAL_PK
        PRIMARY KEY (id_sucursal),

    CONSTRAINT SUCURSAL_FK_CIUDAD
        FOREIGN KEY (cod_ciudad)
        REFERENCES CIUDAD(id_ciudad)
);


-- ============================================================
-- 4. TABLA MARCA
-- ============================================================

CREATE TABLE MARCA (
    id_marca NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,

    CONSTRAINT MARCA_PK
        PRIMARY KEY (id_marca)
);


-- ============================================================
-- 5. TABLA MODELO
-- ============================================================

CREATE TABLE MODELO (
    id_modelo NUMBER(5) NOT NULL,
    marca_id NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,

    CONSTRAINT MODELO_PK
        PRIMARY KEY (id_modelo, marca_id),

    CONSTRAINT MODELO_FK_MARCA
        FOREIGN KEY (marca_id)
        REFERENCES MARCA(id_marca)
);


-- ============================================================
-- 6. TABLA TIPO_AUTOMOVIL
-- ============================================================

CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo CHAR(3) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,

    CONSTRAINT TIPO_AUTOMOVIL_PK
        PRIMARY KEY (id_tipo)
);


-- ============================================================
-- 7. TABLA CLIENTE
-- ============================================================

CREATE TABLE CLIENTE (
    rut NUMBER(8) NOT NULL,
    dv CHAR(1) NOT NULL,
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20) NOT NULL,
    apaterno VARCHAR2(20) NOT NULL,
    amaterno VARCHAR2(20) NOT NULL,
    telefono VARCHAR2(12) NOT NULL,
    email VARCHAR2(40),
    tipo_cli CHAR(1) NOT NULL,

    CONSTRAINT CLIENTE_PK
        PRIMARY KEY (rut)
);


-- ============================================================
-- 8. TABLA ESTANDAR
-- ============================================================

CREATE TABLE ESTANDAR (
    cl_rut NUMBER(8) NOT NULL,
    puntaje_fidelidad NUMBER(10) NOT NULL,

    CONSTRAINT ESTANDAR_PK
        PRIMARY KEY (cl_rut),

    CONSTRAINT ESTANDAR_FK_CLIENTE
        FOREIGN KEY (cl_rut)
        REFERENCES CLIENTE(rut)
);


-- ============================================================
-- 9. TABLA PREMIUM
-- ============================================================

CREATE TABLE PREMIUM (
    cl_rut NUMBER(8) NOT NULL,
    pesos_clientes NUMBER(10) NOT NULL,
    monto_credito NUMBER(10) NOT NULL,

    CONSTRAINT PREMIUM_PK
        PRIMARY KEY (cl_rut),

    CONSTRAINT PREMIUM_FK_CLIENTE
        FOREIGN KEY (cl_rut)
        REFERENCES CLIENTE(rut)
);


-- ============================================================
-- 10. TABLA MECANICO
-- Identity inicia en 460 e incrementa en 7
-- ============================================================

CREATE TABLE MECANICO (
    cod_mecanico NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 460 INCREMENT BY 7),

    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20) NOT NULL,
    apaterno VARCHAR2(20) NOT NULL,
    amaterno VARCHAR2(20) NOT NULL,

    bono_jefatura NUMBER(10),

    sueldo NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10) NOT NULL,
    cod_supervisor NUMBER(5),

    CONSTRAINT MECANICO_PK
        PRIMARY KEY (cod_mecanico),

    CONSTRAINT MECANICO_FK_MECANICO
        FOREIGN KEY (cod_supervisor)
        REFERENCES MECANICO(cod_mecanico)
);


-- ============================================================
-- 11. TABLA AUTOMOVIL
-- ============================================================

CREATE TABLE AUTOMOVIL (
    patente CHAR(8) NOT NULL,
    annio NUMBER(4) NOT NULL,
    cant_puertas NUMBER(1) NOT NULL,
    km NUMBER(6) NOT NULL,
    color VARCHAR2(30) NOT NULL,
    cod_tipo_auto CHAR(3) NOT NULL,
    cod_modelo NUMBER(5) NOT NULL,
    cod_marca NUMBER(2) NOT NULL,
    cl_rut NUMBER(8) NOT NULL,

    CONSTRAINT AUTOMOVIL_PK
        PRIMARY KEY (patente),

    CONSTRAINT AUTOMOVIL_FK_CLIENTE
        FOREIGN KEY (cl_rut)
        REFERENCES CLIENTE(rut),

    CONSTRAINT AUTOMOVIL_FK_MODELO
        FOREIGN KEY (cod_modelo, cod_marca)
        REFERENCES MODELO(id_modelo, marca_id),

    CONSTRAINT AUTOMOVIL_FK_TIPO
        FOREIGN KEY (cod_tipo_auto)
        REFERENCES TIPO_AUTOMOVIL(id_tipo)
);


-- ============================================================
-- 12. TABLA SERVICIO
-- ============================================================

CREATE TABLE SERVICIO (
    id_servicio NUMBER(3) NOT NULL,
    descripcion VARCHAR2(100) NOT NULL,
    costo NUMBER(7) NOT NULL,

    CONSTRAINT SERVICIO_PK
        PRIMARY KEY (id_servicio)
);


-- ============================================================
-- 13. TABLA MANTENCION
-- ============================================================

CREATE TABLE MANTENCION (
    num_mantencion NUMBER(4) NOT NULL,
    cod_sucursal CHAR(3) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_salida DATE,
    patente_auto CHAR(8),
    cod_mecanico NUMBER(5) NOT NULL,
    costo_total NUMBER(7) NOT NULL,
    estado VARCHAR2(15),

    CONSTRAINT MANTENCION_PK
        PRIMARY KEY (num_mantencion),

    CONSTRAINT MANT_FK_AUTOMOVIL
        FOREIGN KEY (patente_auto)
        REFERENCES AUTOMOVIL(patente),

    CONSTRAINT MANT_FK_MECANICO
        FOREIGN KEY (cod_mecanico)
        REFERENCES MECANICO(cod_mecanico),

    CONSTRAINT MANT_FK_SUCURSAL
        FOREIGN KEY (cod_sucursal)
        REFERENCES SUCURSAL(id_sucursal)
);


-- ============================================================
-- 14. TABLA DETALLE_SERVICIO
-- ============================================================

CREATE TABLE DETALLE_SERVICIO (
    mantencion_num NUMBER(4) NOT NULL,
    cod_servicio NUMBER(3) NOT NULL,
    descuento_serv NUMBER(4,3) NOT NULL,
    cantidad NUMBER(3) NOT NULL,

    CONSTRAINT DETALLE_SERVICIO_PK
        PRIMARY KEY (mantencion_num, cod_servicio),

    CONSTRAINT DET_SERV_FK_MANTENCION
        FOREIGN KEY (mantencion_num)
        REFERENCES MANTENCION(num_mantencion),

    CONSTRAINT DET_SERV_FK_SERVICIO
        FOREIGN KEY (cod_servicio)
        REFERENCES SERVICIO(id_servicio)
);



-- ============================================================
-- CASO 2
-- MODIFICACION DEL MODELO MEDIANTE ALTER TABLE
-- ============================================================


-- ============================================================
-- 1. ELIMINAR COSTO_TOTAL DE MANTENCION
-- ============================================================

ALTER TABLE MANTENCION
DROP COLUMN costo_total;


-- ============================================================
-- 2. MODIFICAR LA PK DE MANTENCION
-- ============================================================

ALTER TABLE DETALLE_SERVICIO
DROP CONSTRAINT DET_SERV_FK_MANTENCION;


ALTER TABLE DETALLE_SERVICIO
DROP CONSTRAINT DETALLE_SERVICIO_PK;


-- Eliminar PK antigua de MANTENCION

ALTER TABLE MANTENCION
DROP CONSTRAINT MANTENCION_PK;


-- Crear la nueva PK compuesta de MANTENCION

ALTER TABLE MANTENCION
ADD CONSTRAINT MANTENCION_PK
PRIMARY KEY (num_mantencion, cod_sucursal);


-- Agregar cod_sucursal a DETALLE_SERVICIO

ALTER TABLE DETALLE_SERVICIO
ADD cod_sucursal CHAR(3) NOT NULL;


-- Crear nueva PK de DETALLE_SERVICIO

ALTER TABLE DETALLE_SERVICIO
ADD CONSTRAINT DETALLE_SERVICIO_PK
PRIMARY KEY (
    mantencion_num,
    cod_sucursal,
    cod_servicio
);


-- Crear nuevamente la FK hacia MANTENCION,
-- ahora utilizando la PK compuesta.

ALTER TABLE DETALLE_SERVICIO
ADD CONSTRAINT DET_SERV_FK_MANTENCION
FOREIGN KEY (
    mantencion_num,
    cod_sucursal
)
REFERENCES MANTENCION (
    num_mantencion,
    cod_sucursal
);


-- ============================================================
-- 3. EMAIL DEL CLIENTE NO PUEDE REPETIRSE
-- El campo sigue siendo opcional.
-- ============================================================

ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_UN_EMAIL
UNIQUE (email);


-- ============================================================
-- 4. VALIDAR DIGITO VERIFICADOR DEL CLIENTE
-- ============================================================

ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_CK_DV
CHECK (
    dv IN (
        '0','1','2','3','4',
        '5','6','7','8','9','K'
    )
);


-- ============================================================
-- 5. SUELDO MINIMO DEL MECANICO: $510.000
-- ============================================================

ALTER TABLE MECANICO
ADD CONSTRAINT MECANICO_CK_SUELDO
CHECK (sueldo >= 510000);


-- ============================================================
-- 6. ESTADOS PERMITIDOS PARA UNA MANTENCION
-- ============================================================

ALTER TABLE MANTENCION
ADD CONSTRAINT MANTENCION_CK_ESTADO
CHECK (
    estado IN (
        'Reserva',
        'Ingresado',
        'Entregado',
        'Anulado'
    )
);



-- ============================================================
-- CASO 3
-- POBLAMIENTO DEL MODELO
-- ============================================================


-- ============================================================
-- SECUENCIA PARA SERVICIO
-- Inicia 400 e incrementa en 2:
-- ============================================================

CREATE SEQUENCE SEQ_SERVICIO
START WITH 400
INCREMENT BY 2
NOCACHE
NOCYCLE;


-- ============================================================
-- SECUENCIA PARA CIUDAD
-- Inicia 165 e incrementa en 5:
-- ============================================================

CREATE SEQUENCE SEQ_CIUDAD
START WITH 165
INCREMENT BY 5
NOCACHE
NOCYCLE;



-- ============================================================
-- POBLAMIENTO TABLA PAIS
-- Identity genera automáticamente:
-- Chile = 9
-- Peru = 12
-- Colombia = 15
-- ============================================================

INSERT INTO PAIS (nom_pais)
VALUES ('Chile');

INSERT INTO PAIS (nom_pais)
VALUES ('Peru');

INSERT INTO PAIS (nom_pais)
VALUES ('Colombia');



-- ============================================================
-- POBLAMIENTO TABLA CIUDAD
-- ============================================================

INSERT INTO CIUDAD (
    id_ciudad,
    nom_ciudad,
    cod_pais
)
VALUES (
    SEQ_CIUDAD.NEXTVAL,
    'Santiago',
    9
);


INSERT INTO CIUDAD (
    id_ciudad,
    nom_ciudad,
    cod_pais
)
VALUES (
    SEQ_CIUDAD.NEXTVAL,
    'Lima',
    12
);


INSERT INTO CIUDAD (
    id_ciudad,
    nom_ciudad,
    cod_pais
)
VALUES (
    SEQ_CIUDAD.NEXTVAL,
    'Bogotá',
    15
);



-- ============================================================
-- POBLAMIENTO TABLA SUCURSAL
-- ============================================================

INSERT INTO SUCURSAL (
    id_sucursal,
    nom_sucursal,
    calle,
    num_calle,
    cod_ciudad
)
VALUES (
    'S01',
    'Providencia',
    'Av. A. Varas',
    234,
    165
);


INSERT INTO SUCURSAL (
    id_sucursal,
    nom_sucursal,
    calle,
    num_calle,
    cod_ciudad
)
VALUES (
    'S02',
    'Las 4 esquinas',
    'Av. Latina',
    669,
    170
);


INSERT INTO SUCURSAL (
    id_sucursal,
    nom_sucursal,
    calle,
    num_calle,
    cod_ciudad
)
VALUES (
    'S03',
    'El Cafetero',
    'Av. El Faro',
    900,
    175
);



-- ============================================================
-- POBLAMIENTO TABLA MECANICO.
-- ============================================================


-- 460
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Jorge',
    'Pablo',
    'Soto',
    'Sierpe',
    5400000,
    2759000,
    223580,
    NULL
);


-- 467
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Pedro',
    'Jose',
    'Manriquez',
    'Corral',
    NULL,
    759000,
    23980,
    NULL
);


-- 474
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Sandra',
    'Josefa',
    'Letelier',
    'S.',
    0,
    659000,
    223580,
    460
);


-- 481
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Felipe',
    'M.',
    'Vidal',
    'A.',
    NULL,
    759000,
    23580,
    460
);


-- 488
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Jose',
    'Miguel',
    'Troncoso',
    'B.',
    NULL,
    659000,
    44580,
    474
);


-- 495
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Juan',
    'Pablo',
    'Sánchez',
    'R.',
    NULL,
    859000,
    23380,
    474
);


-- 502
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Carlos',
    'Felipe',
    'Soto',
    'J.',
    0,
    959000,
    23580,
    474
);


-- 509
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Alberto',
    'P.',
    'Cerda',
    'Ramírez',
    NULL,
    559000,
    22380,
    460
);


-- 516
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Alejandra',
    'Gabriela',
    'Infanti',
    'R.',
    NULL,
    659000,
    22380,
    460
);


-- 523
INSERT INTO MECANICO (
    pnombre,
    snombre,
    apaterno,
    amaterno,
    bono_jefatura,
    sueldo,
    monto_impuestos,
    cod_supervisor
)
VALUES (
    'Roberto',
    'Patricio',
    'Gutierrez',
    'Sosa',
    NULL,
    859000,
    22380,
    460
);



-- ============================================================
-- POBLAMIENTO TABLA SERVICIO
-- ============================================================

INSERT INTO SERVICIO (
    id_servicio,
    descripcion,
    costo
)
VALUES (
    SEQ_SERVICIO.NEXTVAL,
    'Cambio Luces',
    45000
);


INSERT INTO SERVICIO (
    id_servicio,
    descripcion,
    costo
)
VALUES (
    SEQ_SERVICIO.NEXTVAL,
    'Desabolladura',
    67000
);


INSERT INTO SERVICIO (
    id_servicio,
    descripcion,
    costo
)
VALUES (
    SEQ_SERVICIO.NEXTVAL,
    'Revisión Frenos',
    30000
);


INSERT INTO SERVICIO (
    id_servicio,
    descripcion,
    costo
)
VALUES (
    SEQ_SERVICIO.NEXTVAL,
    'Cambio Puerta Trasera',
    50000
);



-- ============================================================
-- POBLAMIENTO TABLA MANTENCION
-- patente_auto queda NULL porque así aparece
-- en los datos entregados.
-- ============================================================


INSERT INTO MANTENCION (
    num_mantencion,
    cod_sucursal,
    fecha_ingreso,
    fecha_salida,
    patente_auto,
    cod_mecanico,
    estado
)
VALUES (
    101,
    'S01',
    TO_DATE('12-04-2023', 'DD-MM-YYYY'),
    NULL,
    NULL,
    481,
    'Reserva'
);


INSERT INTO MANTENCION (
    num_mantencion,
    cod_sucursal,
    fecha_ingreso,
    fecha_salida,
    patente_auto,
    cod_mecanico,
    estado
)
VALUES (
    102,
    'S02',
    TO_DATE('21-02-2023', 'DD-MM-YYYY'),
    TO_DATE('21-02-2023', 'DD-MM-YYYY'),
    NULL,
    502,
    'Entregado'
);


INSERT INTO MANTENCION (
    num_mantencion,
    cod_sucursal,
    fecha_ingreso,
    fecha_salida,
    patente_auto,
    cod_mecanico,
    estado
)
VALUES (
    103,
    'S02',
    TO_DATE('09-10-2023', 'DD-MM-YYYY'),
    NULL,
    NULL,
    502,
    'Anulado'
);


INSERT INTO MANTENCION (
    num_mantencion,
    cod_sucursal,
    fecha_ingreso,
    fecha_salida,
    patente_auto,
    cod_mecanico,
    estado
)
VALUES (
    104,
    'S03',
    TO_DATE('11-08-2023', 'DD-MM-YYYY'),
    TO_DATE('18-08-2023', 'DD-MM-YYYY'),
    NULL,
    509,
    'Entregado'
);


INSERT INTO MANTENCION (
    num_mantencion,
    cod_sucursal,
    fecha_ingreso,
    fecha_salida,
    patente_auto,
    cod_mecanico,
    estado
)
VALUES (
    105,
    'S03',
    TO_DATE('03-12-2023', 'DD-MM-YYYY'),
    NULL,
    NULL,
    509,
    'Ingresado'
);


COMMIT;



-- ============================================================
-- CASO 4
-- RECUPERACION DE DATOS
-- ============================================================


-- ============================================================
-- INFORME 1
--
-- Mecánicos:
-- bono_jefatura IS NULL
-- monto_impuestos < 40000
--
-- Impuesto rebajado = impuesto actual * 80%
--
-- Sueldo con rebaja impuestos =
-- sueldo - impuesto rebajado
--
-- Orden:
-- impuesto actual DESC
-- apellido paterno ASC
-- ============================================================

SELECT
    cod_mecanico
        AS "ID MECANICO",

    pnombre || ' ' || apaterno
        AS "NOMBRE MECANICO",

    sueldo
        AS "SALARIO",

    monto_impuestos
        AS "IMPUESTO ACTUAL",

    monto_impuestos * 0.80
        AS "IMPUESTO REBAJADO",

    sueldo - (monto_impuestos * 0.80)
        AS "SUELDO CON REBAJA IMPUESTOS"

FROM MECANICO

WHERE
    bono_jefatura IS NULL
    AND monto_impuestos < 40000

ORDER BY
    monto_impuestos DESC,
    apaterno ASC;



-- ============================================================
-- INFORME 2
--
-- Mecánicos con:
-- sueldo entre 600000 y 900000
-- O
-- sin supervisor
--
-- Ajuste = 5% del sueldo
-- Sueldo reajustado = sueldo + 5%
--
-- Orden:
-- sueldo ASC
-- nombre completo DESC
-- ============================================================

SELECT
    cod_mecanico
        AS "IDENTIFICADOR",

    pnombre || ' ' || snombre || ' ' || apaterno
        AS "MECANICO",

    sueldo
        AS "SALARIO ACTUAL",

    sueldo * 0.05
        AS "AJUSTE",

    sueldo + (sueldo * 0.05)
        AS "SUELDO_REAJUSTADO"

FROM MECANICO

WHERE
    sueldo BETWEEN 600000 AND 900000
    OR cod_supervisor IS NULL

ORDER BY
    sueldo ASC,
    pnombre || ' ' || snombre || ' ' || apaterno DESC;