/* =====================================================
   ACTIVIDAD SEMANA 6 - MODELAMIENTO DE BASES DE DATOS
   Caso: Consultorio Médico Municipalidad Santa Gema
   ===================================================== */


/* =====================================================
   1. ELIMINACIÓN DE OBJETOS
   ===================================================== */

-- DROP TABLE --

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PAGO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DOSIS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RECETA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PACIENTE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIGITADOR CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMUNA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CIUDAD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE REGION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BANCO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

/* =====================================================
   2. CASO 1 - CREACIÓN DE TABLAS Y ALTER TABLE
   ===================================================== */

-- CREATE TABLE --

/* =====================================================
   REGION
   ===================================================== */
CREATE TABLE REGION (
    id_region       NUMBER(2)    NOT NULL,
    nombre_region   VARCHAR2(50) NOT NULL
);

-- PRIMARY KEY
ALTER TABLE REGION
ADD CONSTRAINT region_pk
PRIMARY KEY (id_region);


/* =====================================================
   CIUDAD
   ===================================================== */

CREATE TABLE CIUDAD (
    id_ciudad       NUMBER(5)    NOT NULL,
    nombre_ciudad   VARCHAR2(50) NOT NULL,
    id_region       NUMBER(2)    NOT NULL
);

-- PRIMARY KEY
ALTER TABLE CIUDAD
ADD CONSTRAINT ciudad_pk
PRIMARY KEY (id_ciudad);

-- FOREIGN KEY
ALTER TABLE CIUDAD
ADD CONSTRAINT ciudad_region_fk
FOREIGN KEY (id_region)
REFERENCES REGION(id_region);
        
/* =====================================================
   COMUNA
   ID AUTOINCREMENTABLE
   COMIENZA EN 1101
   ===================================================== */       
   CREATE TABLE COMUNA (
    id_comuna NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1101 INCREMENT BY 1),

    nombre_comuna VARCHAR2(50) NOT NULL,
    id_ciudad     NUMBER(5)    NOT NULL
);

-- PRIMARY KEY
ALTER TABLE COMUNA
ADD CONSTRAINT comuna_pk
PRIMARY KEY (id_comuna);

-- FOREIGN KEY
ALTER TABLE COMUNA
ADD CONSTRAINT comuna_ciudad_fk
FOREIGN KEY (id_ciudad)
REFERENCES CIUDAD(id_ciudad);


/* =====================================================
   ESPECIALIDAD
   ID GENERADO AUTOMATICAMENTE
   ===================================================== */
CREATE TABLE ESPECIALIDAD (
    id_especialidad NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    nombre_especialidad VARCHAR2(50) NOT NULL
);

-- PRIMARY KEY
ALTER TABLE ESPECIALIDAD
ADD CONSTRAINT especialidad_pk
PRIMARY KEY (id_especialidad);
/* =====================================================
   PACIENTE
   ===================================================== */
CREATE TABLE PACIENTE (
    rut_pac       VARCHAR2(25) NOT NULL,
    dv_pac        CHAR(1)      NOT NULL,
    pnombre       VARCHAR2(25) NOT NULL,
    snombre       VARCHAR2(25),
    papellido     VARCHAR2(25) NOT NULL,
    sapellido     VARCHAR2(25),
    edad          NUMBER(3)    NOT NULL,
    telefono      NUMBER(9),
    calle         VARCHAR2(50) NOT NULL,
    numeracion    NUMBER(5)    NOT NULL,
    id_comuna     NUMBER       NOT NULL
);

-- PRIMARY KEY
ALTER TABLE PACIENTE
ADD CONSTRAINT paciente_pk
PRIMARY KEY (rut_pac);

-- FOREIGN KEY
ALTER TABLE PACIENTE
ADD CONSTRAINT paciente_comuna_fk
FOREIGN KEY (id_comuna)
REFERENCES COMUNA(id_comuna);

-- CHECK DEL DIGITO VERIFICADOR
ALTER TABLE PACIENTE
ADD CONSTRAINT paciente_dv_ck
CHECK (
    dv_pac IN
    ('0','1','2','3','4','5','6','7','8','9','K')
);


/* =====================================================
   MEDICO
   ===================================================== */
CREATE TABLE MEDICO (
    rut_med          NUMBER(8)    NOT NULL,
    dv_med           CHAR(1)      NOT NULL,
    pnombre          VARCHAR2(25) NOT NULL,
    snombre          VARCHAR2(25),
    papellido        VARCHAR2(25) NOT NULL,
    sapellido        VARCHAR2(25),
    telefono         NUMBER(9)    NOT NULL,
    id_especialidad  NUMBER       NOT NULL
);

-- PRIMARY KEY
ALTER TABLE MEDICO
ADD CONSTRAINT medico_pk
PRIMARY KEY (rut_med);

-- FOREIGN KEY
ALTER TABLE MEDICO
ADD CONSTRAINT medico_especialidad_fk
FOREIGN KEY (id_especialidad)
REFERENCES ESPECIALIDAD(id_especialidad);

-- UNIQUE
-- Dos medicos no pueden registrar el mismo telefono.
ALTER TABLE MEDICO
ADD CONSTRAINT medico_telefono_un
UNIQUE (telefono);

-- CHECK DEL DIGITO VERIFICADOR
ALTER TABLE MEDICO
ADD CONSTRAINT medico_dv_ck
CHECK (
    dv_med IN
    ('0','1','2','3','4','5','6','7','8','9','K')
);

/* =====================================================
   DIGITADOR
   ===================================================== */
CREATE TABLE DIGITADOR (
    id_digitador   NUMBER(20)   NOT NULL,
    dv_digitador   CHAR(1)      NOT NULL,
    pnombre        VARCHAR2(25) NOT NULL,
    papellido      VARCHAR2(25) NOT NULL
);

-- PRIMARY KEY
ALTER TABLE DIGITADOR
ADD CONSTRAINT digitador_pk
PRIMARY KEY (id_digitador);

-- CHECK DEL DIGITO VERIFICADOR
ALTER TABLE DIGITADOR
ADD CONSTRAINT digitador_dv_ck
CHECK (
    dv_digitador IN
    ('0','1','2','3','4','5','6','7','8','9','K')
);

/* =====================================================
   DIAGNOSTICO
   ===================================================== */
CREATE TABLE DIAGNOSTICO (
    cod_diagnostico NUMBER(3)    NOT NULL,
    nombre          VARCHAR2(50) NOT NULL
);

-- PRIMARY KEY
ALTER TABLE DIAGNOSTICO
ADD CONSTRAINT diagnostico_pk
PRIMARY KEY (cod_diagnostico);

/* =====================================================
   MEDICAMENTO
   ===================================================== */
CREATE TABLE MEDICAMENTO (
    cod_medicamento    NUMBER(7)    NOT NULL,
    nombre             VARCHAR2(50) NOT NULL,
    tipo_medicamento   VARCHAR2(20) NOT NULL,
    dosis_recomendada  VARCHAR2(50) NOT NULL,
    stock              NUMBER(7)    NOT NULL
);

-- PRIMARY KEY
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT medicamento_pk
PRIMARY KEY (cod_medicamento);

-- CHECK
-- El stock no puede ser negativo.
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT medicamento_stock_ck
CHECK (stock >= 0);


/* =====================================================
   RECETA
   ===================================================== */
CREATE TABLE RECETA (
    cod_receta        NUMBER(7)     NOT NULL,
    observaciones     VARCHAR2(500),
    fecha_emision     DATE          NOT NULL,
    fecha_expiracion  DATE,
    tipo_receta       VARCHAR2(20)  NOT NULL,
    rut_pac           VARCHAR2(25)  NOT NULL,
    rut_med           NUMBER(8)     NOT NULL,
    id_digitador      NUMBER(20)    NOT NULL,
    cod_diagnostico   NUMBER(3)     NOT NULL
);

-- PRIMARY KEY
ALTER TABLE RECETA
ADD CONSTRAINT receta_pk
PRIMARY KEY (cod_receta);

-- FOREIGN KEY: PACIENTE
ALTER TABLE RECETA
ADD CONSTRAINT receta_paciente_fk
FOREIGN KEY (rut_pac)
REFERENCES PACIENTE(rut_pac);

-- FOREIGN KEY: MEDICO
ALTER TABLE RECETA
ADD CONSTRAINT receta_medico_fk
FOREIGN KEY (rut_med)
REFERENCES MEDICO(rut_med);

-- FOREIGN KEY: DIGITADOR
ALTER TABLE RECETA
ADD CONSTRAINT receta_digitador_fk
FOREIGN KEY (id_digitador)
REFERENCES DIGITADOR(id_digitador);

-- FOREIGN KEY: DIAGNOSTICO
ALTER TABLE RECETA
ADD CONSTRAINT receta_diagnostico_fk
FOREIGN KEY (cod_diagnostico)
REFERENCES DIAGNOSTICO(cod_diagnostico);

-- CHECK DE TIPO DE RECETA
ALTER TABLE RECETA
ADD CONSTRAINT receta_tipo_ck
CHECK (
    tipo_receta IN
    ('DIGITAL',
     'MAGISTRAL',
     'RETENIDA',
     'GENERAL',
     'VETERINARIA')
);

/* =====================================================
   DOSIS
   ===================================================== */
CREATE TABLE DOSIS (
    cod_receta          NUMBER(7)     NOT NULL,
    cod_medicamento     NUMBER(7)     NOT NULL,
    descripcion_dosis   VARCHAR2(100) NOT NULL
);

-- PRIMARY KEY COMPUESTA
ALTER TABLE DOSIS
ADD CONSTRAINT dosis_pk
PRIMARY KEY (cod_receta, cod_medicamento);

-- FOREIGN KEY: RECETA
ALTER TABLE DOSIS
ADD CONSTRAINT dosis_receta_fk
FOREIGN KEY (cod_receta)
REFERENCES RECETA(cod_receta);

-- FOREIGN KEY: MEDICAMENTO
ALTER TABLE DOSIS
ADD CONSTRAINT dosis_medicamento_fk
FOREIGN KEY (cod_medicamento)
REFERENCES MEDICAMENTO(cod_medicamento);

/* =====================================================
   BANCO
   ===================================================== */
CREATE TABLE BANCO (
    cod_banco     NUMBER(3)    NOT NULL,
    nombre_banco  VARCHAR2(50) NOT NULL
);

-- PRIMARY KEY
ALTER TABLE BANCO
ADD CONSTRAINT banco_pk
PRIMARY KEY (cod_banco);

/* =====================================================
   PAGO
   ===================================================== */
CREATE TABLE PAGO (
    cod_boleta    NUMBER(8)    NOT NULL,
    cod_receta    NUMBER(7)    NOT NULL,
    fecha_pago    DATE         NOT NULL,
    monto_total   NUMBER(10)   NOT NULL,
    metodo_pago   VARCHAR2(20) NOT NULL,
    cod_banco     NUMBER(3)
);

-- PRIMARY KEY
ALTER TABLE PAGO
ADD CONSTRAINT pago_pk
PRIMARY KEY (cod_boleta);

-- FOREIGN KEY: RECETA
ALTER TABLE PAGO
ADD CONSTRAINT pago_receta_fk
FOREIGN KEY (cod_receta)
REFERENCES RECETA(cod_receta);

-- FOREIGN KEY: BANCO
ALTER TABLE PAGO
ADD CONSTRAINT pago_banco_fk
FOREIGN KEY (cod_banco)
REFERENCES BANCO(cod_banco);

-- CHECK DEL MONTO
ALTER TABLE PAGO
ADD CONSTRAINT pago_monto_ck
CHECK (monto_total > 0);

/* =====================================================
   3. CASO 2 - MODIFICACIONES
   ===================================================== */

-- ALTER TABLE--

/* ============================================================
   AGREGAR PRECIO UNITARIO A MEDICAMENTO
   ============================================================ */

ALTER TABLE MEDICAMENTO
ADD precio_unitario NUMBER(10);


/* El precio debe estar entre $1.000 y $2.000.000 */

ALTER TABLE MEDICAMENTO
ADD CONSTRAINT medicamento_precio_ck
CHECK (
    precio_unitario BETWEEN 1000 AND 2000000
);

/* ============================================================
   METODOS DE PAGO PERMITIDOS
   ============================================================ */

ALTER TABLE PAGO
ADD CONSTRAINT pago_metodo_ck
CHECK (
    metodo_pago IN
    ('EFECTIVO',
     'TARJETA',
     'TRANSFERENCIA')
);

/* ============================================================
   ELIMINAR EDAD DEL PACIENTE
   ============================================================ */

ALTER TABLE PACIENTE
DROP COLUMN edad;

/* ============================================================
   AGREGAR FECHA DE NACIMIENTO
   ============================================================ */

ALTER TABLE PACIENTE
ADD fecha_nacimiento DATE;

